// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using AppKit;

namespace Formula1Downloader
{
	public partial class ChooseVideos : NSViewController
	{
		public ChooseVideos (IntPtr handle) : base (handle)
		{
		}

		public override CoreGraphics.CGSize PreferredContentSize =>
			new CoreGraphics.CGSize(this.View.Frame.Size.Width, this.View.Frame.Size.Height);

		#region Computed Properties
		public List<Video> Videos { get; set; }
		public NSViewController Presentor { get; set; }
		public VideoTableDataSource DataSource { get; private set; }
		#endregion

		#region Override Methods
		public override void ViewWillAppear ()
		{
			base.ViewWillAppear ();

			DataSource = new VideoTableDataSource(Videos);

			VideosTable.DataSource = DataSource;
			VideosTable.Delegate = new VideoTableDelegate (DataSource);
		}
		#endregion

		#region Private Methods
		private void CloseDialog() {
			Presentor.DismissViewController (this);
		}
		#endregion

		#region Custom Actions
		partial void AcceptSheet (NSObject sender) {
			CloseDialog();
			RaiseDialogAccepted();
		}
		#endregion

		#region Events
		public EventHandler DialogAccepted;

		private void RaiseDialogAccepted() {
			DialogAccepted?.Invoke(this, EventArgs.Empty);
		}
		#endregion
	}
}
